@startgantt
Title Project Timeline

Project starts 2024-09-01
printscale weekly
saturday are closed
sunday are closed

[Recording Development Process] starts 2024-09-01 and ends 2024-11-31
[Recording Development Process] --> [Report Writing]

[Report Writing] starts 2024-08-01 and ends 2024-12-26

[Submission to Vitec MV] starts 2024-12-26 and ends 2025-01-02
[Report Writing] --> [Submission to Vitec MV]

[Deadline for Delivery of Project Description] starts 2024-08-31 and ends 2024-08-31

[Official start of project] starts 2024-09-01 and ends 2024-09-01


[Start of prototyping process] starts 2024-09-01 and ends 2024-09-15
[Start of prototyping process] --> [Skeleton and initial API definitions]
[Start of prototyping process] --> [Produce Graphical Mockups]

[Preliminary Research] starts 2024-09-01 and ends 2024-09-30

[Skeleton and initial API definitions] starts 2024-09-15 and ends 2024-09-30
[Produce Graphical Mockups] starts 2024-09-15 and ends 2024-09-30
[Skeleton and initial API definitions] --> [Deployment to Test Environment]

[Deployment to Test Environment] starts 2024-10-01 and ends 2024-10-15
[Deployment to Test Environment] --> [Building out Services and Integration Testing]

[Building out Services and Integration Testing] starts 2024-10-15 and ends 2024-10-31
[Building out Services and Integration Testing] --> [Architecture Functional]

[Architecture Functional] starts 2024-11-01 and ends 2024-11-15
[MVP complete] starts 2024-11-15 and ends 2025-01-02
[Architecture Functional] --> [MVP complete]

[MVP complete] --> [Project Deadline]


@endgantt
